name: schedule

on:
  schedule:
    # NOTE: 间隔 5 分钟执行一次
    - cron: "*/600 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install deno
        uses: denolib/setup-deno@master

      - name: Run deno
        run: |
          git config --local user.email "imrealleonardo@gmail.com"
          git config --local user.name "Lishuang"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          deno run --unstable --allow-net --allow-read --allow-write --import-map=import_map.json mod.ts
          git add .
          git commit -m "-update by github action;"
          git push
